image: ${DOCKER_IMAGE}

variables:
  GIT_SUBMODULE_STRATEGY:         recursive
  ANDROID_PLATFORM_VERSION_OEFFI: android-31
  ANDROID_BUILD_TOOLS_VERSION:    33.0.0
  ANDROID_HOME:                   $PWD/android-sdk

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install ${JDK_PACKAGE}
  - apt-get -y install sdkmanager gradle
  - yes | sdkmanager --licenses >/dev/null || true
  - sdkmanager --install "platforms;$ANDROID_PLATFORM_VERSION_OEFFI" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

build:
  parallel:
    matrix:
      - DOCKER_IMAGE: [ ubuntu:jammy, debian:bookworm-slim ]
        JDK_PACKAGE: [ openjdk-11-jdk-headless ]
  script:
    - gradle build --stacktrace
